### ISSUE TITLE
Can provide more detail about how to init a puzzle?

### ISSUE THREAD

**Issue by Jekinnnnnn** [hkociemba/WaterBallSortPuzzleOptimalSolver#1]
I am interested in randomize function which is the code to generate puzzle ,but I did not learn Pascal.
So can you explain the detail of generate puzzle?
It would be nice if it could be written again in c++

**Comment by hkociemba** [comment]
It just randomly shuffles the NVOLUME * NCOLORS elements of the NCOLORS filled monochromatic vials, each with volume NVOLUME. The Fisher-Yates shuffle does this job.
